### ISSUE TITLE
The Wire.requestFrom should not be encapsulated by Wire.beginTransmission or Wire.endTransmission.

### ISSUE THREAD

**Issue by Koepel** [Seeed-Studio/NFC_Tag_M24LR6E#2]
In the file NfcTag.cpp, in the functions _EEPROM_Read_Byte and _EEPROM_Read_Bytes, there is a Wire.beginTransmission before the Wire.requestFrom and a Wire.endTransmission after it.

Those Wire.beginTransmission and Wire.endTransmission can be removed, they should only be used when writing data.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

There is a PR that solves this problem. I will review and merge it as soon as possible.

**Comment by Lesords** [comment]
Done，

I'm going to close this issue, feel free to re-open it if you have any other questions.
